import type { LessonData } from '@/data/lessons'

export const esLessons: Record<number, Partial<LessonData>> = {
  0: {
    title: "¡Bienvenido al Futuro – Tu Aventura de IA Comienza!",
    introduction: "¡Adéntrate en el laboratorio tecnológico mágico donde todo es posible! Maya y Alex miraban una pantalla holográfica brillante cuando un robot amigable y reluciente llamado Vision Vee flotó hacia abajo para saludarlos. '¡Bienvenidos, jóvenes exploradores!', gorjeó Vee. 'Están a punto de comenzar un viaje súper emocionante en la Inteligencia Artificial, la Robótica y las increíbles tecnologías del mañana. ¿Están listos para ver cómo la IA está cambiando nuestro mundo?'",
    main_lesson: "La Inteligencia Artificial (o IA) es como darles a las computadoras un tipo especial de 'poder cerebral' para que puedan ayudarnos a resolver problemas, reconocer imágenes, entender nuestras voces ¡e incluso crear arte! Al igual que tú aprendes leyendo libros y jugando juegos, las computadoras pueden aprender de patrones e información. A lo largo de este viaje, visitarás diferentes islas virtuales y aprenderás cómo la IA hace que los autos se conduzcan solos, ayuda a los médicos a curar enfermedades, protege a los animales salvajes y hace que el futuro sea más brillante para todos.",
    examples: [{ type: "activity", content: "Mira a tu alrededor: desde asistentes inteligentes hasta bloqueos faciales, la IA ya está aquí ayudándote todos los días. ¿Puedes identificar 3 cosas impulsadas por IA?" }],
    fun_facts: ["¿Sabías que la palabra 'robot' se usó por primera vez en una obra de teatro hace más de 100 años? ¡Hoy en día, robots reales e IA nos ayudan a explorar el espacio profundo y el fondo del océano!"]
  },
  1: {
    title: "Visión Artificial – Enseñando a Ver a las Computadoras",
    introduction: "En lo profundo del brillante Heavenly Tech Lab, Maya descubrió algo increíble. '¿Cómo sabe mi tableta que soy yo?', se preguntó. De repente, apareció Vision Vee, rodeada de un mágico brillo holográfico. '¡Hola Maya!', dijo Vee con calidez. '¡Al igual que nosotros vemos la belleza del mundo, yo uso la Visión Artificial para ver y entender los patrones inteligentes que nos rodean! ¿Quieres unirte a mi aventura?'",
    main_lesson: "La Visión Artificial es un regalo especial para las computadoras. Les enseña a ver y comprender el maravilloso mundo, de la misma manera que nuestros ojos y corazones trabajan juntos para reconocer a las personas que amamos. Las computadoras usan cámaras y sensores para capturar imágenes, y luego usan algoritmos inteligentes para encontrar patrones en esas imágenes, como identificar rostros, leer texto o detectar un gato en una foto. Empresas como Google y Apple usan la Visión Artificial en cada aplicación de fotos y función de desbloqueo facial que usas todos los días. Los autos autónomos la usan para leer las señales de tránsito. Los médicos la usan para detectar enfermedades en escaneos médicos. ¡Las posibilidades son infinitas!",
    fun_facts: ["¿Sabías que la cámara de tu teléfono inteligente realiza aproximadamente 1,000 millones de cálculos cada segundo solo para enfocar tu rostro cuando te tomas una selfie? ¡Eso es más rápido que un parpadeo!", "Los sistemas de visión artificial ahora pueden identificar más de 10,000 tipos diferentes de objetos en una sola imagen."],
    examples: [{ type: "activity", content: "Mira alrededor de tu habitación y elige 5 objetos. Escríbelos. Ahora imagina entrenar a una computadora para reconocer cada uno: ¿qué pistas le enseñarías a buscar? ¿Color, forma, tamaño?" }]
  },
  2: {
    title: "Reconocimiento de Voz – Enseñando a Escuchar a las Computadoras",
    introduction: "A Alex le encanta hablar con sus dispositivos inteligentes en casa. De repente, aparece Echo Ed, un robot con patrones de ondas de sonido brillantes como una onda digital en un estanque. '¡Hola Alex!', explica Echo Ed con una sonrisa. '¡Tu voz es como una hermosa canción! Ayudo a las computadoras a captar tus palabras y convertirlas en ideas inteligentes. ¡Es como ser un detective de la música invisible del habla!'",
    main_lesson: "El Reconocimiento de Voz ayuda a las computadoras a escuchar con el corazón. Transforma el sonido de nuestras voces en palabras que ayudan a la IA a comprender cómo puede ayudarnos mejor. Cuando hablas con Siri o Alexa, tu voz se descompone en pequeñas ondas sonoras. La IA analiza esas ondas, las compara con patrones que ha aprendido de millones de voces y las convierte en texto en milisegundos. El reconocimiento de voz se usa en centros de llamadas, hospitales (para que los médicos dicten notas), en autos (para controlar la música o los mapas) y para ayudar a las personas con discapacidades a comunicarse mejor.",
    fun_facts: ["El primer sistema de reconocimiento de voz se creó en 1952 y solo podía entender los números del 0 al 9, pero los sistemas actuales pueden entender millones de palabras en cientos de idiomas.", "Los altavoces inteligentes ahora pueden entender acentos de más de 50 países."],
    examples: [{ type: "activity", content: "Di una frase con claridad y luego intenta decir la misma frase en un susurro. Pídele a un amigo o familiar que lo intente también. ¿Cómo cambia el sonido? ¡Esta es exactamente la variación que la IA debe aprender a manejar!" }]
  },
  3: {
    title: "Traducción de IA – Rompiendo las Barreras del Idioma",
    introduction: "Sofía quiere ser amiga de Yuki de Japón, pero hablan idiomas diferentes. De repente, aparece Linky Lex sosteniendo un globo digital brillante. '¡Te ayudaré a construir un puente de amistad!', dice Lex. 'Conozco las reglas de muchos idiomas y puedo convertir tus palabras al japonés para que Yuki pueda entender tu corazón. ¡Es como un puente mágico de bondad!'",
    main_lesson: "La Traducción de IA es como un puente mágico que conecta a personas de todo el mundo. Los sistemas modernos usan la Traducción Automática Neuronal: la IA lee oraciones completas en lugar de palabra por palabra, comprendiendo el contexto y el significado. Fue entrenada con miles de millones de oraciones en parejas (como una oración en inglés junto a su versión en español) para aprender a mapear los idiomas. Hoy en día, Google Translate maneja más de 500 millones de solicitudes de traducción al día, admitiendo más de 100 idiomas.",
    fun_facts: ["¡Google Translate puede traducir entre más de 100 idiomas y procesa más de 500 millones de solicitudes de traducción todos los días!", "La IA ahora puede traducir el lenguaje de señas en texto y el texto de regreso a lenguaje de señas animado."],
    examples: [{ type: "activity", content: "Elige un saludo de 5 países diferentes (por ejemplo, Bonjour, Hola, Konnichiwa, Ciao, Salaam). ¡Intenta decirlo! Ahora piensa: ¿cómo aprendería una IA a traducir entre todos estos?" }]
  }
}
