import type { LessonData } from '@/data/lessons'

export const frLessons: Record<number, Partial<LessonData>> = {
  0: {
    title: "Bienvenue dans le Futur – Votre Aventure IA Commence !",
    introduction: "Entrez dans le laboratoire technologique magique où tout est possible ! Maya et Alex regardaient un écran holographique brillant lorsqu'un robot amical et brillant nommé Vision Vee est descendu pour les saluer. 'Bienvenue, jeunes explorateurs !' gazouilla Vee. 'Vous êtes sur le point de commencer un voyage super excitant dans l'Intelligence Artificielle, la Robotique et les technologies étonnantes de demain. Êtes-vous prêts à voir comment l'IA change notre monde ?'",
    main_lesson: "L'Intelligence Artificielle (ou IA) consiste à donner aux ordinateurs une sorte de 'cerveau' pour qu'ils puissent nous aider à résoudre des problèmes, à reconnaître des images, à comprendre nos voix et même à créer de l'art ! Tout comme vous apprenez en lisant des livres et en jouant à des jeux, les ordinateurs peuvent apprendre à partir de modèles et d'informations. Au cours de ce voyage, vous visiterez différentes îles virtuelles et apprendrez comment l'IA permet aux voitures de se conduire toutes seules, aide les médecins à guérir les maladies, protège les animaux sauvages et rend l'avenir plus brillant pour tout le monde.",
    examples: [{ type: "activity", content: "Regardez autour de vous — des assistants intelligents aux verrouillages faciaux, l'IA est déjà là pour vous aider au quotidien. Pouvez-vous repérer 3 choses alimentées par l'IA ?" }],
    fun_facts: ["Saviez-vous que le mot 'robot' a été utilisé pour la première fois dans une pièce de théâtre il y a plus de 100 ans ? Aujourd'hui, de vrais robots et l'IA nous aident à explorer l'espace lointain et le fond de l'océan !"]
  },
  1: {
    title: "Vision par Ordinateur – Apprendre aux Ordinateurs à Voir",
    introduction: "Au fond du Heavenly Tech Lab brillant, Maya a découvert quelque chose d'incroyable. 'Comment ma tablette sait-elle que c'est moi ?' se demanda-t-elle. Soudain, Vision Vee apparut, entourée d'un éclat holographique magique. 'Salut Maya !' dit chaleureusement Vee. 'Tout comme nous voyons la beauté du monde, j'utilise la Vision par Ordinateur pour voir et comprendre les schémas intelligents qui nous entourent ! Tu veux te joindre à mon aventure ?'",
    main_lesson: "La Vision par Ordinateur est un cadeau spécial pour les ordinateurs ! Elle leur apprend à voir et à comprendre le monde merveilleux, tout comme nos yeux et nos cœurs travaillent ensemble pour reconnaître les personnes que nous aimons. Les ordinateurs utilisent des caméras et des capteurs pour capturer des images, puis utilisent des algorithmes intelligents pour trouver des motifs dans ces images — comme identifier des visages, lire du texte ou repérer un chat sur une photo. Des entreprises comme Google et Apple utilisent la Vision par Ordinateur dans chaque application photo et fonction de déverrouillage facial que vous utilisez au quotidien. Les voitures autonomes l'utilisent pour lire les panneaux de signalisation. Les médecins l'utilisent pour détecter les maladies dans les scanners médicaux. Les possibilités sont infinies !",
    fun_facts: ["Saviez-vous que l'appareil photo de votre smartphone effectue environ 1 milliard de calculs chaque seconde juste pour faire la mise au point sur votre visage lors d'un selfie ? C'est plus rapide qu'un battement de cils !", "Les systèmes de vision par ordinateur peuvent désormais identifier plus de 10 000 types d'objets différents dans une seule image."],
    examples: [{ type: "activity", content: "Regardez autour de votre pièce et choisissez 5 objets. Notez-les. Imaginez maintenant que vous entraînez un ordinateur à reconnaître chacun d'eux — quels indices lui apprendriez-vous à rechercher ? Couleur, forme, taille ?" }]
  },
  2: {
    title: "Reconnaissance Vocale – Apprendre aux Ordinateurs à Écouter",
    introduction: "Alex adore parler à ses instruments intelligents à la maison. Soudain, Echo Ed, un robot avec des motifs d'ondes sonores lumineuses comme une ondulation numérique sur un étang, apparaît. 'Salut Alex !' explique Echo Ed avec un sourire. 'Ta voix est comme une belle chanson ! J'aide les ordinateurs à capter tes mots et à les transformer en idées intelligentes. C'est comme être un détective pour la musique invisible de la parole !'",
    main_lesson: "La Reconnaissance Vocale aide les ordinateurs à écouter avec leur cœur ! Elle transforme le son de nos voix en mots qui aident l'IA à comprendre comment elle peut nous aider au mieux. Lorsque vous parlez à Siri ou à Alexa, votre voix est décomposée en minuscules ondes sonores. L'IA analyse ces ondes, les compare aux modèles qu'elle a appris à partir de millions de voix et les convertit en texte en quelques millisecondes. La reconnaissance vocale est utilisée dans les centres d'appels, les hôpitaux (pour permettre aux médecins de dicter des notes), dans les voitures (pour contrôler la musique ou les cartes) et pour aider les personnes handicapées à mieux communiquer.",
    fun_facts: ["Le premier système de reconnaissance vocale a été créé en 1952 et ne pouvait comprendre que les chiffres 0 à 9, mais les systèmes d'aujourd'hui peuvent comprendre des millions de mots dans des centaines de langues !", "Les enceintes intelligentes peuvent désormais comprendre les accents de plus de 50 pays."],
    examples: [{ type: "activity", content: "Dites une phrase clairement, puis essayez de dire la même phrase dans un chuchotement. Demandez à un ami ou à un membre de votre famille d'essayer aussi. Comment le son change-t-il ? C'est exactement le genre de variation que l'IA doit apprendre à gérer !" }]
  },
  3: {
    title: "Traduction IA – Briser les Barrières de la Langue",
    introduction: "Sofia veut être amie avec Yuki du Japon, mais ils parlent des langues différentes. Soudain, Linky Lex apparaît, tenant un globe numérique brillant. 'Je vais t'aider à construire un pont d'amitié !' dit Lex. 'Je connais les règles de nombreuses langues et je peux transformer tes mots en japonais pour que Yuki puisse comprendre ton cœur. C'est comme un pont magique de gentillesse !'",
    main_lesson: "La Traduction par IA est comme un pont magique reliant les gens du monde entier ! Les systèmes de traduction modernes utilisent ce qu'on appelle la Traduction Machine Neuronale — l'IA lit des phrases entières plutôt que mot par mot, comprenant le contexte et la signification derrière les mots. Elle a été entraînée sur des milliards de phrases par paires (comme une phrase en anglais à côté de sa version française) afin d'apprendre comment les langues se correspondent. Aujourd'hui, Google Traduction traite plus de 500 millions de requêtes de traduction chaque jour, prenant en charge plus de 100 langues.",
    fun_facts: ["Google Traduction peut traduire entre plus de 100 langues et traite plus de 500 millions de requêtes de traduction chaque jour !", "L'IA peut désormais traduire la langue des signes en texte et le texte en langue des signes animée."],
    examples: [{ type: "activity", content: "Choisissez une salutation de 5 pays différents (par exemple, Bonjour, Hola, Konnichiwa, Ciao, Salaam). Essayez de les dire ! Pensez maintenant : comment une IA apprendrait-elle à traduire entre toutes ces langues ?" }]
  }
}
